"""Reusable Manim components for layout-categories explanations."""

from .style import BACKGROUND, CODE_FONT, INK, MODE_COLORS, MUTED, PANEL
from .animations import (
    DrawMapstoTip,
    TailToTipMapsto,
    TailToTipUnmapsto,
    TipToTailUnmapsto,
    UncreateMapstoTip,
    UndrawMapstoTip,
)
from .coalesce import (
    cell_weld_box_frame,
    cell_weld_hull,
    cell_weld_product_box,
    cell_weld_seams,
    coalesce_partitions,
    correspondence_line_frame,
    correspondence_lines,
    correspondence_pull_arrow,
    interpolate_mapsto_arrow,
    selective_corner_box,
)
from .composition import TupleMorphismCompositionDiagram, compose_tuple_maps
from .nested_tuple import NestedTupleTree
from .nest_morphism import NestMorphismDiagram
from .paths import (
    ARROW_BEND_HANDLE,
    ARROW_ENDPOINT_INSET,
    ARROW_HORIZONTAL_RUN,
    append_cubic_segments,
    bridge,
    horizontal_matched_path_pair,
    join_route,
    matched_path_pair,
    repartition_path,
    split_cubic,
    three_segment_route,
)
from .ref_trees import ref_tree_segments, ref_tree_with_paths
from .scene_base import LayoutScene
from .stacks import (
    ARROW_INSET,
    ARROW_RUN,
    CELL_H,
    FONT_SIZE,
    LABEL_FONT_SIZE,
    LEFT_X,
    MAX_STACK_HEIGHT,
    MID_X,
    REVEAL,
    RIGHT_X,
    ROW_GAP,
    SLOT_STEP,
    STROKE_WIDTH,
    TAIL_LENGTH,
    TIP_LENGTH,
    TIP_WIDTH,
    arrow_tip,
    attached,
    cell,
    deck,
    leaf_groups,
    make_place,
    revealed,
    segment_arrow,
    split_cell,
    tree_segment,
)
from .tuple_morphism import MapstoArrow, TupleMorphismDiagram

__all__ = [
    "BACKGROUND",
    "CODE_FONT",
    "INK",
    "MODE_COLORS",
    "MUTED",
    "PANEL",
    "LayoutScene",
    "MapstoArrow",
    "NestedTupleTree",
    "NestMorphismDiagram",
    "DrawMapstoTip",
    "TailToTipMapsto",
    "TailToTipUnmapsto",
    "TipToTailUnmapsto",
    "UncreateMapstoTip",
    "UndrawMapstoTip",
    "TupleMorphismCompositionDiagram",
    "TupleMorphismDiagram",
    "cell_weld_box_frame",
    "cell_weld_hull",
    "cell_weld_product_box",
    "cell_weld_seams",
    "coalesce_partitions",
    "compose_tuple_maps",
    "correspondence_line_frame",
    "correspondence_lines",
    "correspondence_pull_arrow",
    "interpolate_mapsto_arrow",
    "selective_corner_box",
    # paths
    "ARROW_BEND_HANDLE",
    "ARROW_ENDPOINT_INSET",
    "ARROW_HORIZONTAL_RUN",
    "append_cubic_segments",
    "bridge",
    "horizontal_matched_path_pair",
    "join_route",
    "matched_path_pair",
    "repartition_path",
    "split_cubic",
    "three_segment_route",
    # ref trees
    "ref_tree_segments",
    "ref_tree_with_paths",
    # stacks
    "ARROW_INSET",
    "ARROW_RUN",
    "CELL_H",
    "FONT_SIZE",
    "LABEL_FONT_SIZE",
    "LEFT_X",
    "MAX_STACK_HEIGHT",
    "MID_X",
    "REVEAL",
    "RIGHT_X",
    "ROW_GAP",
    "SLOT_STEP",
    "STROKE_WIDTH",
    "TAIL_LENGTH",
    "TIP_LENGTH",
    "TIP_WIDTH",
    "arrow_tip",
    "attached",
    "cell",
    "deck",
    "leaf_groups",
    "make_place",
    "revealed",
    "segment_arrow",
    "split_cell",
    "tree_segment",
]
